#!/bin/bash
# Automated tests for .claude/scripts/lib/profile.sh
#
# Usage:
#   bash tests/test-profile-lib.sh       # Run all tests
#   bash tests/test-profile-lib.sh -q    # Quiet mode
#   bash tests/test-profile-lib.sh -v    # Verbose mode
#
# Exit codes:
#   0 - All tests passed
#   1 - Some tests failed

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TOOLKIT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROFILE_LIB="$TOOLKIT_DIR/.claude/scripts/lib/profile.sh"

source "$SCRIPT_DIR/lib/test-helpers.sh"
parse_test_args "$@"

# === Environment ===

TEMP_DIR=""

setup_test_env() {
    TEMP_DIR=$(mktemp -d)
    log_verbose "Created temp dir: $TEMP_DIR"
}

teardown_test_env() {
    if [[ -n "$TEMP_DIR" && -d "$TEMP_DIR" ]]; then
        rm -rf "$TEMP_DIR"
        log_verbose "Cleaned up temp dir: $TEMP_DIR"
    fi
    TEMP_DIR=""
}

# Invoke detect_profile in a subshell so each call gets a fresh sourcing
# (the library uses an idempotency guard via _PROFILE_SOURCED).
# Usage: call_detect <root> [env_project_root]
call_detect() {
    local root="$1"
    local env_root="${2:-}"
    if [[ -n "$env_root" ]]; then
        PROJECT_ROOT="$env_root" bash -c "source '$PROFILE_LIB' && detect_profile '$root'"
    else
        bash -c "source '$PROFILE_LIB' && detect_profile '$root'"
    fi
}

call_detect_env_only() {
    local env_root="$1"
    PROJECT_ROOT="$env_root" bash -c "source '$PROFILE_LIB' && detect_profile"
}

call_detect_pwd() {
    local cwd="$1"
    (cd "$cwd" && bash -c "source '$PROFILE_LIB' && detect_profile")
}

assert_profile() {
    local description="$1"
    local expected="$2"
    local actual="$3"

    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$actual" == "$expected" ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        report_pass "$description"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        report_fail "$description"
        report_detail "Expected: $expected"
        report_detail "Actual:   $actual"
    fi
}

# === Tests ===

report_section "=== profile.sh: toolkit detection ==="
setup_test_env
mkdir -p "$TEMP_DIR/docs/indexes"
touch "$TEMP_DIR/docs/indexes/SKILLS.md"
# Also seed a .claude/MANIFEST with a different profile — toolkit must still win.
mkdir -p "$TEMP_DIR/.claude"
printf '# profile: base\n' > "$TEMP_DIR/.claude/MANIFEST"
assert_profile "toolkit repo detected via docs/indexes/SKILLS.md (wins over MANIFEST)" \
    "toolkit" "$(call_detect "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: base consumer ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
printf '# profile: base\n# Auto-generated by claude-toolkit sync\n\nskills/foo/\n' > "$TEMP_DIR/.claude/MANIFEST"
assert_profile "base profile from marker" "base" "$(call_detect "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: raiz consumer ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
printf '# profile: raiz\n\nskills/foo/\n' > "$TEMP_DIR/.claude/MANIFEST"
assert_profile "raiz profile from marker" "raiz" "$(call_detect "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: unknown (empty dir) ==="
setup_test_env
assert_profile "empty dir returns unknown" "unknown" "$(call_detect "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: unknown (MANIFEST without marker in first 5) ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
cat > "$TEMP_DIR/.claude/MANIFEST" <<'EOF'
# Some other header
# More comments
skills/foo/
skills/bar/
skills/baz/
# profile: base
EOF
assert_profile "marker past 5-line window → unknown" \
    "unknown" "$(call_detect "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: robustness — leading blanks + unrelated comments ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
cat > "$TEMP_DIR/.claude/MANIFEST" <<'EOF'


# Some preamble

# profile: raiz
EOF
assert_profile "blank lines + one preamble comment before marker → raiz" \
    "raiz" "$(call_detect "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: positional override beats PROJECT_ROOT ==="
setup_test_env
mkdir -p "$TEMP_DIR/arg/.claude" "$TEMP_DIR/env/.claude"
printf '# profile: raiz\n' > "$TEMP_DIR/arg/.claude/MANIFEST"
printf '# profile: base\n' > "$TEMP_DIR/env/.claude/MANIFEST"
assert_profile "arg=raiz, env=base → raiz (arg wins)" \
    "raiz" "$(call_detect "$TEMP_DIR/arg" "$TEMP_DIR/env")"
teardown_test_env

report_section "=== profile.sh: PROJECT_ROOT env fallback ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
printf '# profile: base\n' > "$TEMP_DIR/.claude/MANIFEST"
assert_profile "PROJECT_ROOT env used when no arg passed" \
    "base" "$(call_detect_env_only "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: pwd fallback ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
printf '# profile: raiz\n' > "$TEMP_DIR/.claude/MANIFEST"
assert_profile "pwd used when no arg and no PROJECT_ROOT" \
    "raiz" "$(call_detect_pwd "$TEMP_DIR")"
teardown_test_env

report_section "=== profile.sh: rejects ## (double-hash) ==="
setup_test_env
mkdir -p "$TEMP_DIR/.claude"
cat > "$TEMP_DIR/.claude/MANIFEST" <<'EOF'
##profile: base
# also not a match
EOF
assert_profile "##profile: is not matched → unknown" \
    "unknown" "$(call_detect "$TEMP_DIR")"
teardown_test_env

print_summary
